{
 "title": "Rodent Infestation Model Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total inference requests per borough",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "predict_requests_total", "legendFormat": "{{borough}}" }
   ]
  },
  {
   "title": "Model Accuracies",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "model_accuracy", "legendFormat": "{{borough}}" }
   ]
  },
  {
   "title": "Rate of requests to each borough(1m)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(predict_requests_total[1m])\n",
     "legendFormat": "{{borough}}"
    }
   ]
  }
 ]
}