{
 "title": "NYC Rat Infestation",
 "time": { "from": "2023-01-01T05:00:00.000Z", "to": "2025-05-01T04:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "month",
    "label": "month",
    "query": "SELECT DISTINCT month FROM all_radius ORDER BY month;"
   },
   {
    "name": "boro",
    "label": "boro",
    "query": "SELECT DISTINCT boro FROM all_radius ORDER BY boro;"
   },
   {
    "name": "complaints",
    "label": "Complaints",
    "query": "rat_complaints_0.1mi,rat_complaints_0.2mi,rat_complaints_0.3mi,rat_complaints_0.4mi,rat_complaints_0.5mi,rat_complaints_0.6mi,rat_complaints_0.7mi,rat_complaints_0.8mi,rat_complaints_0.9mi,rat_complaints_1.0mi,building_count_0.1mi,building_count_0.2mi,building_count_0.3mi,building_count_0.4mi,building_count_0.5mi"
   },
   { "name": "camis", "label": "Restaurant unique ID", "query": "30075445" },
   {
    "name": "dba",
    "label": "Restaurant name",
    "query": "SELECT dba FROM all_radius WHERE camis = '${camis}'"
   }
  ]
 },
 "panels": [
  {
   "title": "Heatmap of rat complaints / building counts per month per radius",
   "type": "geomap",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "queryText": "SELECT camis, dba AS name, boro, latitude, longitude, \"month\", score,\n  CASE\n    WHEN 'rat_complaints_0.7mi' = 'rat_complaints_0.1mi' THEN \"rat_complaints_0.1mi\"\n    WHEN 'rat_complaints_0.7mi' = 'rat_complaints_0.2mi' THEN \"rat_complaints_0.2mi\"\n    WHEN 'rat_complaints_0.7mi' = 'rat_complaints_0.3mi' THEN \"rat_complaints_0.3mi\"\n    WHEN 'rat_complaints_0.7mi' = 'rat_complaints_0.4mi' THEN \"rat_complaints_0.4mi\"\n    WHEN 'rat_complaints_0.7mi' = 'rat_complaints_0.5mi' THEN \"rat_complaints_0.5mi\"\n    WHEN 'rat_complaints_0.7mi' = 'rat_complaints_0.6mi' THEN \"rat_complaints_0.6mi\"\n    WHEN 'rat_complaints_0.7mi' = 'rat_complaints_0.7mi' THEN \"rat_complaints_0.7mi\"\n    WHEN 'rat_complaints_0.7mi' = 'rat_complaints_0.8mi' THEN \"rat_complaints_0.8mi\"\n    WHEN 'rat_complaints_0.7mi' = 'rat_complaints_0.9mi' THEN \"rat_complaints_0.9mi\"\n    WHEN 'rat_complaints_0.7mi' = 'rat_complaints_1.0mi' THEN \"rat_complaints_1.0mi\"\n    WHEN 'rat_complaints_0.7mi' = 'building_count_0.1mi' THEN \"building_count_0.1mi\"\n    WHEN 'rat_complaints_0.7mi' = 'building_count_0.2mi' THEN \"building_count_0.2mi\"\n    WHEN 'rat_complaints_0.7mi' = 'building_count_0.3mi' THEN \"building_count_0.3mi\"\n    WHEN 'rat_complaints_0.7mi' = 'building_count_0.4mi' THEN \"building_count_0.4mi\"\n    WHEN 'rat_complaints_0.7mi' = 'building_count_0.5mi' THEN \"building_count_0.5mi\"\n  END AS counts\nFROM all_radius\nWHERE month = '2025-01'\nAND boro IN ('Bronx','Brooklyn','Manhattan','Queens','Staten Island');\n",
     "rawQueryText": "SELECT camis, dba AS name, boro, latitude, longitude, \"month\", score,\n  CASE\n    WHEN '${complaints}' = 'rat_complaints_0.1mi' THEN \"rat_complaints_0.1mi\"\n    WHEN '${complaints}' = 'rat_complaints_0.2mi' THEN \"rat_complaints_0.2mi\"\n    WHEN '${complaints}' = 'rat_complaints_0.3mi' THEN \"rat_complaints_0.3mi\"\n    WHEN '${complaints}' = 'rat_complaints_0.4mi' THEN \"rat_complaints_0.4mi\"\n    WHEN '${complaints}' = 'rat_complaints_0.5mi' THEN \"rat_complaints_0.5mi\"\n    WHEN '${complaints}' = 'rat_complaints_0.6mi' THEN \"rat_complaints_0.6mi\"\n    WHEN '${complaints}' = 'rat_complaints_0.7mi' THEN \"rat_complaints_0.7mi\"\n    WHEN '${complaints}' = 'rat_complaints_0.8mi' THEN \"rat_complaints_0.8mi\"\n    WHEN '${complaints}' = 'rat_complaints_0.9mi' THEN \"rat_complaints_0.9mi\"\n    WHEN '${complaints}' = 'rat_complaints_1.0mi' THEN \"rat_complaints_1.0mi\"\n    WHEN '${complaints}' = 'building_count_0.1mi' THEN \"building_count_0.1mi\"\n    WHEN '${complaints}' = 'building_count_0.2mi' THEN \"building_count_0.2mi\"\n    WHEN '${complaints}' = 'building_count_0.3mi' THEN \"building_count_0.3mi\"\n    WHEN '${complaints}' = 'building_count_0.4mi' THEN \"building_count_0.4mi\"\n    WHEN '${complaints}' = 'building_count_0.5mi' THEN \"building_count_0.5mi\"\n  END AS counts\nFROM all_radius\nWHERE month = '${month}'\nAND boro IN (${boro:sqlstring});\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Restaurant timeline for ${dba}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 22 },
   "targets": [
    {
     "queryText": "SELECT '30075445', dba, month,\nCASE\n    WHEN 'rat_complaints_0.7mi' = 'rat_complaints_0.1mi' THEN \"rat_complaints_0.1mi\"\n    WHEN 'rat_complaints_0.7mi' = 'rat_complaints_0.2mi' THEN \"rat_complaints_0.2mi\"\n    WHEN 'rat_complaints_0.7mi' = 'rat_complaints_0.3mi' THEN \"rat_complaints_0.3mi\"\n    WHEN 'rat_complaints_0.7mi' = 'rat_complaints_0.4mi' THEN \"rat_complaints_0.4mi\"\n    WHEN 'rat_complaints_0.7mi' = 'rat_complaints_0.5mi' THEN \"rat_complaints_0.5mi\"\n    WHEN 'rat_complaints_0.7mi' = 'rat_complaints_0.6mi' THEN \"rat_complaints_0.6mi\"\n    WHEN 'rat_complaints_0.7mi' = 'rat_complaints_0.7mi' THEN \"rat_complaints_0.7mi\"\n    WHEN 'rat_complaints_0.7mi' = 'rat_complaints_0.8mi' THEN \"rat_complaints_0.8mi\"\n    WHEN 'rat_complaints_0.7mi' = 'rat_complaints_0.9mi' THEN \"rat_complaints_0.9mi\"\n    WHEN 'rat_complaints_0.7mi' = 'rat_complaints_1.0mi' THEN \"rat_complaints_1.0mi\"\n    WHEN 'rat_complaints_0.7mi' = 'building_count_0.1mi' THEN \"building_count_0.1mi\"\n    WHEN 'rat_complaints_0.7mi' = 'building_count_0.2mi' THEN \"building_count_0.2mi\"\n    WHEN 'rat_complaints_0.7mi' = 'building_count_0.3mi' THEN \"building_count_0.3mi\"\n    WHEN 'rat_complaints_0.7mi' = 'building_count_0.4mi' THEN \"building_count_0.4mi\"\n    WHEN 'rat_complaints_0.7mi' = 'building_count_0.5mi' THEN \"building_count_0.5mi\"\n  END AS counts\nFROM all_radius\nWHERE camis = '30075445';",
     "rawQueryText": "SELECT '${camis}', dba, month,\nCASE\n    WHEN '${complaints}' = 'rat_complaints_0.1mi' THEN \"rat_complaints_0.1mi\"\n    WHEN '${complaints}' = 'rat_complaints_0.2mi' THEN \"rat_complaints_0.2mi\"\n    WHEN '${complaints}' = 'rat_complaints_0.3mi' THEN \"rat_complaints_0.3mi\"\n    WHEN '${complaints}' = 'rat_complaints_0.4mi' THEN \"rat_complaints_0.4mi\"\n    WHEN '${complaints}' = 'rat_complaints_0.5mi' THEN \"rat_complaints_0.5mi\"\n    WHEN '${complaints}' = 'rat_complaints_0.6mi' THEN \"rat_complaints_0.6mi\"\n    WHEN '${complaints}' = 'rat_complaints_0.7mi' THEN \"rat_complaints_0.7mi\"\n    WHEN '${complaints}' = 'rat_complaints_0.8mi' THEN \"rat_complaints_0.8mi\"\n    WHEN '${complaints}' = 'rat_complaints_0.9mi' THEN \"rat_complaints_0.9mi\"\n    WHEN '${complaints}' = 'rat_complaints_1.0mi' THEN \"rat_complaints_1.0mi\"\n    WHEN '${complaints}' = 'building_count_0.1mi' THEN \"building_count_0.1mi\"\n    WHEN '${complaints}' = 'building_count_0.2mi' THEN \"building_count_0.2mi\"\n    WHEN '${complaints}' = 'building_count_0.3mi' THEN \"building_count_0.3mi\"\n    WHEN '${complaints}' = 'building_count_0.4mi' THEN \"building_count_0.4mi\"\n    WHEN '${complaints}' = 'building_count_0.5mi' THEN \"building_count_0.5mi\"\n  END AS counts\nFROM all_radius\nWHERE camis = '${camis}';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Total records",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT COUNT(*) AS total_records FROM all_radius;",
     "rawQueryText": "SELECT COUNT(*) AS total_records FROM all_radius;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}